### ISSUE TITLE
Use Cases / Diagramm

### ISSUE THREAD

**Issue by ThierryGirod** [ThierryGirod/whatshouldieat#1]
Primary idea is to have a web application that supports a user with various recipe ideas.
- What can I cook today based on favourite recipes.
- Random recommendation of recipes.
- What can I cook with the ingredients x,y and z left in the fridge?
- Takeouts near me?

**Comment by ThierryGirod** [comment]
- Grocery list from the recommended recipe.
- Random recommendation could be in tinder style with swiping left and right
- Weekly meal planner
- Meal history

**Comment by ThierryGirod** [comment]
- Onboarding process to get user preferences f.ex. vegan, meatless etc.

**Comment by ofaust90** [comment]
- Sharing suggested meal with a partner/friend via whatsapp

**Comment by ofaust90** [comment]
Recipe Model definition:

@Entity
public class FoodItem {

    @Id
    @GeneratedValue
    @Getter
    @Setter
    private Integer id;
    
    @Getter
    @Setter
    private String name;

    @Getter
    @Setter
    private String ingredients = "n/a";

    @Getter
    @Setter
    private String cookingInstructions = "n/a";

    @Getter
    @Setter
    private String imageUrl = "";

    @Getter
    @Setter
    private String additionalInformation = "";

**Comment by ThierryGirod** [comment]
Prio 1 / Version 1:

- What can I cook today based on favourite recipes.
- Random recommendation of recipes.
- What can I cook with the ingredients x,y and z left in the fridge?
- Takeouts near me?
- Sharing suggested meal with a partner/friend via whatsapp

Prio 2:
- Grocery list from the recommended recipe.
- Random recommendation could be in tinder style with swiping left and right
- Weekly meal planner
- Meal history
- Onboarding process to get user preferences f.ex. vegan, meatless etc.
